# **Курс "Програмування на мові Python"**

##### Викладачі:
##### Борисенко Павло Борисович
##### Щьоголєв Максим Олегович


## **Практичне зайняття №8**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажання можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [26]:
import numpy as np
import itertools

def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    matrix = np.random.randint(10, size = (dim, dim))
    return matrix

def permutations(dim):
    """
    The function generetes all permutations in range from 1 to dim.
    """
    str
    t = list(itertools.permutations('', dim))
    return t



def compositions():
    """
    The function generetes all compositions of permutations in range from 1 to dim.
    """
    

def summa():
    """
    The function generetes summa of all compositions.
    """



n = input('Enter n: ')

try:
    n = int(n)
except ValueError:
    print('It has to be an integer number!')
    n = int(input('Enter n: '))

try:
    if n <= 0:
        raise ValueError('The number has to be more than zero!')
except ValueError as ve:
    print(ve)
    n = int(input('Enter n: '))

print(random_matrix(n))

# print(summa(compositions(permutations(n)))

It has to be an integer number!
The number has to be more than zero!
[[5 5 8 1 6]
 [1 0 9 2 1]
 [8 3 1 7 0]
 [5 1 9 2 4]
 [7 5 7 0 7]]
